## **Machine Learning**

#### **What is Machine Learning?**

Machine Learning is a branch of Artificial Intelligence (AI) that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.

## Prerequisites

In the previous notebook, we learned how to:

- Create the feature matrix (`X`) and target variable (`y`)
- Encode categorical features
- Scale numerical features
- Split the dataset into training and testing sets

For this notebook, we will recreate these variables so that the notebook can be executed independently.

In [ ]:
# Import Required Libraries

import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split

In [7]:
# Load the cleaned dataset
df = pd.read_csv("student_performance_cleaned.csv")

In [8]:
# Select the Target Variable

y = df["marks"]

In [9]:
# Select Input Features
X = df.drop(columns=["marks",'full_name','student_id','email','city','admission_date','scholarship'])

In [10]:
# Create OneHotEncoder Object
onehot_encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

# Apply One-Hot Encoding
encoded_data = onehot_encoder.fit_transform(
    X[["department", "gender"]]
)

# Convert Encoded Data into DataFrame
encoded_df = pd.DataFrame(
    encoded_data,
    columns=onehot_encoder.get_feature_names_out(["department", "gender"]),
    index=X.index
)

# Remove Original Columns
X = X.drop(columns=["department", "gender"])

# Combine Encoded Columns with Remaining Features
X = pd.concat([X, encoded_df], axis=1)

# Display the Result
X.head()

,age,semester,attendance_percentage,tuition_fee,department_AI,department_CS,department_DS,department_IT,department_SE,gender_female,gender_male
0,20,4,80.800000,15000.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,23,6,86.600000,30000.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,18,1,85.100000,50000.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,19,2,85.200000,30000.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,18,1,84.205941,25000.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
# Display Feature Names

X.columns

Index(['age', 'semester', 'attendance_percentage', 'tuition_fee',
       'department_AI', 'department_CS', 'department_DS', 'department_IT',
       'department_SE', 'gender_female', 'gender_male'],
      dtype='str')

In [12]:
# Display Summary Statistics

X.describe()

,age,semester,attendance_percentage,tuition_fee,department_AI,department_CS,department_DS,department_IT,department_SE,gender_female,gender_male
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,21.124138,4.020690,84.688699,27068.965517,0.186207,0.248276,0.131034,0.234483,0.200000,0.379310,0.620690
std,2.201271,2.265284,8.858742,10778.486271,0.390623,0.433510,0.338608,0.425144,0.401386,0.486897,0.486897
min,18.000000,1.000000,18.000000,15000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,2.000000,84.205941,15000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,21.000000,4.000000,84.205941,30000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,23.000000,6.000000,89.100000,30000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,25.000000,8.000000,94.900000,50000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
# Create MinMaxScaler Object

minmax_scaler = MinMaxScaler()

In [14]:
# Select Numerical Features

numerical_features = [
    "age",
    "semester",
    "attendance_percentage",
    "tuition_fee"
]

In [15]:
# Apply Min-Max Scaling

X_minmax = X.copy()

X_minmax[numerical_features] = minmax_scaler.fit_transform(
    X_minmax[numerical_features]
)

# Display the First Five Records

X_minmax.head()

,age,semester,attendance_percentage,tuition_fee,department_AI,department_CS,department_DS,department_IT,department_SE,gender_female,gender_male
0,0.285714,0.428571,0.816645,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,0.714286,0.714286,0.892068,0.428571,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0.000000,0.000000,0.872562,1.000000,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.142857,0.142857,0.873862,0.428571,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.000000,0.000000,0.860936,0.285714,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_minmax,
    y,
    test_size=0.20,
    random_state=42
)

In [17]:
# Display the shape of each dataset
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (116, 11)
X_test : (29, 11)
y_train: (116,)
y_test : (29,)

In [18]:
# Display the first five rows of the testing features
X_test.head()

,age,semester,attendance_percentage,tuition_fee,department_AI,department_CS,department_DS,department_IT,department_SE,gender_female,gender_male
69,0.285714,0.142857,0.849155,0.428571,0.0,0.0,1.0,0.0,0.0,0.0,1.0
140,0.000000,0.000000,0.860936,1.000000,0.0,0.0,0.0,0.0,1.0,1.0,0.0
27,0.285714,0.285714,0.916775,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0
19,0.857143,0.714286,0.860936,0.428571,0.0,1.0,0.0,0.0,0.0,1.0,0.0
42,1.000000,0.857143,0.860936,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [19]:
# Display the first five rows of the testing features
y_test.head()

69     73
140    82
27     86
19     79
42     90
Name: marks, dtype: int64

In [20]:
# Display the first five values of the testing target
X_train.head()

,age,semester,attendance_percentage,tuition_fee,department_AI,department_CS,department_DS,department_IT,department_SE,gender_female,gender_male
9,0.142857,0.000000,0.860936,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.000000,0.000000,0.860936,0.285714,1.0,0.0,0.0,0.0,0.0,0.0,1.0
26,1.000000,0.857143,0.849155,0.428571,0.0,0.0,0.0,0.0,1.0,1.0,0.0
120,0.000000,0.000000,0.932380,1.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0
125,0.000000,0.000000,0.931079,1.000000,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [21]:
# Display the first five values of the training target
y_train.head()

9      79
4      82
26     82
120    84
125    85
Name: marks, dtype: int64

#### Train Your First Machine Learning Model

In [29]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [30]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE : 5.136698394629359
MSE : 37.04592556866444
RMSE: 6.086536418084134
R² Score: 0.07308034620829484

In [33]:
# comparison table
results = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": y_pred
})

results.head(10)

     Actual Marks  Predicted Marks
69             73        77.950374
140            82        77.411117
27             86        80.283000
19             79        78.913622
42             90        78.267840
117            94        83.624643
126            74        75.989683
108            78        77.664512
84             88        82.093831
18             78        79.929074